import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import QueryClientProvider from "@/providers/query-client.provider";

import "./globals.css";

const monserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat Pdf RAG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `antialiased min-h-screen bg-background`,
          monserrat.className,
        )}
      >
        <QueryClientProvider>
          <NuqsAdapter>
            {children}
            <Toaster
              richColors
              expand
              position="top-right"
              toastOptions={{
                className:
                  "rounded-2xl shadow-lg border border-border bg-card text-card-foreground",
                duration: 4000,
              }}
            />
          </NuqsAdapter>
        </QueryClientProvider>
      </body>
    </html>
  );
}
